### ISSUE TITLE
when will this code

### ISSUE THREAD

**Issue by azxzxx** [HeranYang/hyper-GAE#1]

**Comment by azxzxx** [comment]
when will this code be released?

**Comment by HeranYang** [comment]
Thanks for your interests on our work. Currently I am working on some other work, and I will try my best to finish the code cleaning&annotating and release this code soon, maybe within next week!

**Comment by HeranYang** [comment]
@azxzxx Hi, I have uploaded our codes for both synthesis and segmentation, and feel free to contact us if there is any problem.
